version: '3.6'

services:
  centrifugal-redis:
    image: redis
    networks:
      - webnet
    ports:
      - "6378:6379"
  centrifugal:
    image: centrifugo/centrifugo
    command: centrifugo -c config.json --engine=redis --redis_address=redis://centrifugal-redis:6379
    ports:
      - "8089:8000"
    networks:
      - webnet
    depends_on:
      - centrifugal-redis
    volumes:
      - "./config:/centrifugo"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
  yjs-api:
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: on-failure
    networks:
      - webnet
    depends_on:
      - centrifugal
    working_dir: /code
    ports:
      - 8088:80
    volumes:
      - ./:/code
    entrypoint: ./entrypoint.sh
    command:
      - |
        poetry install
        gunicorn --reload -k "uvicorn.workers.UvicornWorker" -c "/code/gunicorn_conf.py" "main:app"

networks:
  webnet:
